-- Seed second standard drill: Iron Pressure.
-- 1x3 grid direction drill, 3 sets of 5, random clubs, requires launch monitor.

INSERT INTO "Drill" (
  "DrillID",
  "UserID",
  "Name",
  "SkillArea",
  "DrillType",
  "ScoringMode",
  "InputMode",
  "MetricSchemaID",
  "GridType",
  "SubskillMapping",
  "ClubSelectionMode",
  "TargetDistanceMode",
  "TargetDistanceValue",
  "TargetSizeMode",
  "TargetSizeWidth",
  "TargetSizeDepth",
  "RequiredSetCount",
  "RequiredAttemptsPerSet",
  "Anchors",
  "Target",
  "Description",
  "TargetDistanceUnit",
  "TargetSizeUnit",
  "RequiredEquipment",
  "Origin",
  "Status",
  "IsDeleted",
  "CreatedAt",
  "UpdatedAt"
) VALUES (
  'a0000000-0000-4000-8000-000000000002',
  NULL,
  'Iron Pressure',
  'Approach',
  'Pressure',
  'Shared',
  'GridCell',
  'grid_1x3_direction',
  'OneByThree',
  '["approach_direction_control"]'::JSONB,
  'Random',
  'ClubCarry',
  NULL,
  'PercentageOfTargetDistance',
  NULL,
  NULL,
  3,
  5,
  '{"approach_direction_control": {"Min": 25, "Scratch": 60, "Pro": 90}}'::JSONB,
  NULL,
  'Hit three sets of five shots within the target',
  NULL,
  NULL,
  '["LaunchMonitor"]'::JSONB,
  'System',
  'Active',
  false,
  NOW(),
  NOW()
);
