-- Seed standard drill: Pitch Precision Grid
-- 3×3 grid pitching drill scoring distance and direction control.
-- 5 sets of 3 shots to a fixed 70-yard target (8y wide × 10y deep).

INSERT INTO "Drill" (
  "DrillID",
  "UserID",
  "Name",
  "SkillArea",
  "DrillType",
  "ScoringMode",
  "InputMode",
  "MetricSchemaID",
  "GridType",
  "SubskillMapping",
  "ClubSelectionMode",
  "TargetDistanceMode",
  "TargetDistanceValue",
  "TargetSizeMode",
  "TargetSizeWidth",
  "TargetSizeDepth",
  "RequiredSetCount",
  "RequiredAttemptsPerSet",
  "Anchors",
  "Target",
  "Description",
  "TargetDistanceUnit",
  "TargetSizeUnit",
  "RequiredEquipment",
  "Origin",
  "Status",
  "IsDeleted",
  "CreatedAt",
  "UpdatedAt"
) VALUES (
  'a0000000-0000-4000-8000-000000000003',
  NULL,
  'Pitch Precision Grid',
  'Pitching',
  'Transition',
  'MultiOutput',
  'GridCell',
  'grid_3x3_multioutput',
  'ThreeByThree',
  '["pitching_distance_control", "pitching_direction_control"]'::JSONB,
  'UserLed',
  'Fixed',
  70.0,
  'Fixed',
  8.0,
  10.0,
  5,
  3,
  '{"pitching_distance_control": {"Min": 1, "Scratch": 60, "Pro": 90}, "pitching_direction_control": {"Min": 1, "Scratch": 60, "Pro": 90}}'::JSONB,
  NULL,
  'Pitch 5 sets of 3 shots to a 70-yard target. Score distance and direction control on a 3×3 grid. Target zone: 8 yards wide × 10 yards deep.',
  'yards',
  'yards',
  '[]'::JSONB,
  'System',
  'Active',
  false,
  NOW(),
  NOW()
);
